### ISSUE TITLE
Update to 1.4.6

### ISSUE THREAD

**Issue by Erdmut** [roman-agri/waedichoerbli-junto#14]

**Comment by padili** [comment]
@Erdmut heute Abend habe ich den Release 1.4.6 getested und die Produktion updated.
Ich hoffe, es funktioniert noch alles wie es soll 🙈 
Ansonsten bitte zeitnah melden 💪

**Comment by Erdmut** [comment]
hab grad nur kurz reingeschaut und mir ist eines aufgefallen: wenn man auf "alle Arbeitseinsätze anzeigen" geht, dann ist in der mobilen version eine komische darstellung mit jedesmal einem eingabefeld dabei...

eine super änderung ist das ansonsten und sieht gut aus!

**Comment by padili** [comment]
![AlleEinsätzeMobile](https://user-images.githubusercontent.com/25586157/149829186-c6539d4e-3d08-4e29-ba25-1e52abf6cfe1.jpeg)

**Comment by padili** [comment]
@Erdmut 
David meint es sei ein Cache Problem und werde sich erledigen, wenn der Cache abläuft ... keine Ahnung wie das auf dem Handy läuft 😋  ein Fix für den Cache gibts im Release 1.5
