### ISSUE TITLE
Default Arbeitsbereich bei Neuanmeldung

### ISSUE THREAD

**Issue by padili** [roman-agri/waedichoerbli-junto#8]
Hallo Patricia,

weil es mir gerade wieder in den Sinn kommt, hier etwas das mich schon öfter beschäftigt hat: wir haben einen Tätigkeitsbereich "Aktiv (bekommen alle Mails)" eingerichtet. Wer dort dabei ist, dem schicken wir die Mails über die Filterfunktion. In diesen Tätigkeitsbereich trage ich also jeweils alle Mitglieder die sich neu anmelden manuell ein. Und wenn ein Probeabo zb. abgelaufen ist, müssen wir die Leute manuell wieder austragen. Was recht mühsam ist, weil es leicht vergessen geht und die Namen beim ein und austragen nicht irgendwie sortiert sind.
Meine Idee wäre daher:
1. Vielleicht wäre es möglich, dass ein Mitglied, das sich registriert, automatisch von Beginn an in diesen Tätigkeitsbereich hinzugefügt wird?
2. Gibt es einen Link, den man in die Mails setzen könnte, wo die Leute mit einem Klick darauf, sich aus diesem Tätigkeitsbereich wieder austragen können?

lg. Erdi

**Comment by padili** [comment]
Neuer Business Process
Todo @padili in Juntagrico schauen, ob ein solcher Issue bereits besteht

**Comment by padili** [comment]
juntagrico Issue gfunden 😄 und ist sogar bereits in Arbeit.
https://github.com/juntagrico/juntagrico/issues/452

**Comment by nixnuex** [comment]
Closed through https://github.com/juntagrico/juntagrico/pull/462
